version: 1.0
jobs:
  build:
    working_directory: ~/trello-ui-testing
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Build production
          command: npm run prod
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting